name: Youtube ALL

on:
  schedule:
    - cron: '0 */2 * * *' # Run every 2 hours
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out repository
      - uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Cache Python packages
      - name: Cache pip packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install Python packages
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install additional packages
      - name: Install additional packages
        run: |
          pip install selenium streamlink yt_dlp pytube youtube-dl beautifulsoup4 lxml --upgrade youtube_dl ipython




      # Install ffmpeg
      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      # Execute Python script
      - name: Execute Python script
        run: python YoutubeALL.py

      # Commit files
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update data" -a

      # Get current date
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date '+%Y-%m-%d')"

      # Push changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
