name: Youtube ALL


on:
  schedule:
    - cron: '0 */2 * * *' # run every 2 hours
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Selenium
        run: pip install selenium

      - name: Install Streamlink
        run: pip install streamlink
        
      - name: Install yt_dlp
        run: pip install yt_dlp

      - name: Install pytube
        run: pip install pytube

      - name: Install youtube-dl
        run: pip install youtube-dl

      - name: Install pip install beautifulsoup4
        run: pip install beautifulsoup4
      
      - name: Install pip install lxml
        run: pip install lxml

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Execute Python script
        run: | 
          python YoutubeALL.py
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update data" -a
      - name: Get current date and time
        id: datetime
        run: echo "::set-output name=datetime::$(date '+%Y-%m-%d-%H-%M-%S')"

      - name: Create temporary branch
        run: git checkout -b "temp-${{ steps.datetime.outputs.datetime }}"

      - name: Push temporary branch to origin
        run: git push origin "temp-${{ steps.datetime.outputs.datetime }}"

      - name: Reset working branch
        run: git reset --hard origin/"temp-${{ steps.datetime.outputs.datetime }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "temp-${{ steps.datetime.outputs.datetime }}"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Update data: ${{ steps.datetime.outputs.datetime }}"
          base: main
